// Cleaned, de-duplicated list of client companies extracted from the
// SR_HAMALI_2026-27.xlsx and VIJETA_2026-27.xlsx workbooks (COMPANY
// column, all sheets, Mar-Aug 2026). The raw column had ~224 distinct
// strings full of typos and inconsistent spelling (e.g. GARRETT /
// GARRATT / GARRENT / CARRETT all meant the same client); those were
// merged into 145 canonical names here. Non-company rows ("****",
// "10% DEDUCTION", "TOTAL", "PREVIOUS BILL 10%", etc.) were dropped.
//
// This is a starting point, not a locked list — Admins can add, rename,
// or disable companies any time from Admin > Companies (Owner/Labour
// just pick from whatever Admin has active).
export const WORKBOOK_COMPANY_NAMES: string[] = [
  "AKAR",
  "AUTO",
  "Activ",
  "Adhik",
  "Advik",
  "Air Int",
  "Airport",
  "Akhin",
  "Akuin",
  "Alfapace",
  "Alhat Poly",
  "Alikn Pol",
  "Allied Poly",
  "Allied Wheel",
  "Ampheinol",
  "Anandji",
  "Atlas",
  "Atlascopco",
  "Auto Tech",
  "Autoliv",
  "BTS",
  "Bajaj",
  "Balaji",
  "Baramati",
  "Canon",
  "Carraro",
  "Chennai",
  "Creater",
  "Creative",
  "DAL",
  "DSE",
  "DSL",
  "Danfos",
  "Delhi",
  "Delight",
  "Devine",
  "Dfl Buket",
  "Diachang",
  "Freedumberg",
  "Fukoku",
  "GK FT",
  "GKN",
  "Gabrial",
  "Gaikwad",
  "Garrett",
  "Gujrat",
  "HMT",
  "HUF",
  "Hanon",
  "Hunday Motor",
  "Hundayai",
  "I.M.Gaur",
  "Iljin",
  "Indian",
  "Indian Cast",
  "Inteva",
  "Jayshree",
  "Jyoti",
  "K.M Seat",
  "KSPG",
  "Kalyani",
  "Kamal Tools",
  "Kores",
  "M&M",
  "M&M Bts",
  "M&M J",
  "M&M Kamble",
  "M&M Kanhe",
  "M..Logistics",
  "M.Heavey",
  "M.Logi",
  "MSHK",
  "MSKH",
  "Mahak",
  "Mahale",
  "Mahale Subros",
  "Mahindra",
  "Maqurett",
  "Maruti",
  "Minda",
  "Minda Corpo",
  "Miracle",
  "Motherson",
  "Mumbai",
  "Nashik",
  "Navashiva",
  "New Gen",
  "Nexteer",
  "Octoliv",
  "Ognibene",
  "Omega Steel",
  "Panse",
  "Placraft",
  "Placratt Eng",
  "Plastic",
  "Plasto",
  "Polyrub",
  "Pradeep",
  "Precap",
  "Precomp",
  "Profillo",
  "Profoll",
  "Progresh",
  "RSB",
  "Ramse",
  "Rediant",
  "SKCM",
  "SPM",
  "SR LOG",
  "SRL",
  "Sambhajinagar",
  "Sanaswadi",
  "Sanex",
  "Sanjay",
  "Senex",
  "Shirur",
  "Shivam",
  "Shivam Logi",
  "Shivneri Trans",
  "Shree Packers",
  "Shubham",
  "Sidhi",
  "Smart Log",
  "Spack",
  "Spaco",
  "Subros",
  "Sundaran",
  "Sunex",
  "Suprajeet",
  "Swastik",
  "Tata Ficosa",
  "Trend",
  "Trimurty",
  "Trtera",
  "Uno Minda",
  "VBM",
  "Vahan Logi",
  "Valeo",
  "Varroc",
  "Vijeta",
  "Vitesco",
  "Vveo Tech",
  "Wadki",
  "Yazhaki",
  "Yoonwoo",
];
